// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var context = new AudioContext();

var oscillator = context.createOscillator();

exports.context = context;
exports.oscillator = oscillator;
/* context Not a pure module */
