// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var OscillatorNode = /* module */[];

var AudioContext = /* module */[/* OscillatorNode */OscillatorNode];

exports.AudioContext = AudioContext;
/* No side effect */
